"""
Schema creation for Milestone 6.

This is deliberately NOT a full Alembic migration chain yet. With the
schema still actively taking shape (Milestone 7's PostgreSQL-dependent
work, and likely further columns from later milestones), introducing
Alembic's versioned-migration machinery now would mean maintaining
migration scripts against a schema that hasn't stabilized - premature
process overhead for no current benefit. `init_db()` (create_all, which is
idempotent and additive-only) is the right tool until the schema settles.

When the schema does stabilize (a natural point: once Milestone 7's
frontend is consuming these tables and schema changes need to preserve
existing data rather than being freely re-creatable), switch to Alembic:
    pip install alembic
    alembic init backend/database/migrations
    alembic revision --autogenerate -m "initial schema"
That first autogenerated revision will match database/models.py exactly,
since Alembic introspects it - this file is that migration in spirit, just
without the version-tracking table Alembic would add.

Run directly to create tables:
    python -m backend.database.migrations.create_tables
"""

from backend.database.connection import init_db
from backend.utils.logger import get_logger

logger = get_logger(__name__)


def run() -> None:
    logger.info("Creating database schema...")
    init_db()
    logger.info("Database schema ready.")


if __name__ == "__main__":
    run()
