"""
Sync-thread -> asyncio bridge.

FastAPI's websocket support runs on an asyncio event loop. Alerts and
response events, however, are generated by worker threads (DetectionService's
ThreadPoolExecutor from Milestone 5; response_service.py reuses the same
thread in Milestone 8 - see that module) - ordinary synchronous Python, no
event loop. `publish_event_threadsafe()` is the seam: safe to call from any
thread, schedules the actual broadcast onto the loop captured at startup via
`asyncio.run_coroutine_threadsafe`.

Milestone 8: generalized from "alert-only" to "any event type" -
`publish_alert_threadsafe`/`broadcast_alert` are kept as thin backward-compatible
wrappers so alert_service.py needed no changes.
"""

from __future__ import annotations

import asyncio
from typing import Optional

from backend.utils.logger import get_logger
from backend.websocket.events import WSEventType, serialize_event
from backend.websocket.manager import ConnectionManager, connection_manager

logger = get_logger(__name__)


class AlertBroadcaster:
    def __init__(self, manager: ConnectionManager):
        self.manager = manager
        self._loop: Optional[asyncio.AbstractEventLoop] = None

    def bind_loop(self, loop: asyncio.AbstractEventLoop) -> None:
        """Called once from main.py's lifespan (`asyncio.get_running_loop()`) so this instance knows where to schedule broadcasts."""
        self._loop = loop

    async def broadcast_event(self, event_type: str, payload: dict) -> None:
        message = serialize_event(event_type, payload)
        await self.manager.broadcast(message)

    async def broadcast_alert(self, alert_payload: dict) -> None:
        await self.broadcast_event(WSEventType.ALERT, alert_payload)

    def publish_event_threadsafe(self, event_type: str, payload: dict) -> None:
        """
        Call from any (sync) thread. No-ops with a warning if no event loop
        has been bound yet (e.g. the app hasn't started, or this is being
        exercised outside a running FastAPI app, such as a standalone script).
        """
        if self._loop is None:
            logger.warning("AlertBroadcaster has no bound event loop; skipping WebSocket broadcast of a '%s' event", event_type)
            return
        asyncio.run_coroutine_threadsafe(self.broadcast_event(event_type, payload), self._loop)

    def publish_alert_threadsafe(self, alert_payload: dict) -> None:
        """Backward-compatible alias for publish_event_threadsafe(WSEventType.ALERT, ...)."""
        self.publish_event_threadsafe(WSEventType.ALERT, alert_payload)


# Process-wide instance - imported by main.py (to bind the loop),
# alert_service.py, and response_service.py (to publish), mirroring the
# prediction_service singleton pattern.
broadcaster = AlertBroadcaster(connection_manager)
