/**
 * SOC Platform - Electron main process.
 *
 * Responsibilities:
 *   - Single-instance lock + foreground shell.
 *   - Spawns the local Python security engine (FastAPI/uvicorn):
 *       dev  -> venv python + desktop_entry.py (cwd = ids-platform)
 *       prod -> bundled SOC-Engine.exe (cwd = per-user data dir)
 *   - Waits for the engine's /health endpoint, then opens the dashboard.
 *       dev  -> http://localhost:5173 (Vite dev server, spawned here too)
 *       prod -> http://127.0.0.1:8000 (engine serves the built frontend)
 *   - Manages per-user configuration/secrets/database under
 *     %LOCALAPPDATA%\SOC-Platform (never shipped inside the installer).
 *   - Cleanly kills every child process on quit (taskkill /T /F on Windows).
 *   - Logs everything to <dataRoot>\logs\desktop.log / backend.log.
 */

"use strict";

const { app, BrowserWindow, dialog } = require("electron");
const { spawn, execFileSync } = require("child_process");
const crypto = require("crypto");
const fs = require("fs");
const http = require("http");
const path = require("path");

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const PRODUCT = "SOC-Platform";
const DEFAULT_PORT = 8000;
const VITE_PORT = 5173;
const HEALTH_TIMEOUT_MS = 120_000;
const HEALTH_POLL_MS = 500;

const isPackaged = app.isPackaged;

// Repo layout in dev:
//   <repo>\ids-platform
//     frontend\  backend\  venv\  models\  desktop_entry.py
// <repo>\desktop
//   src\main.cjs   (this file)
const REPO_ROOT = path.resolve(__dirname, "..", "..");
const IDS_PLATFORM_ROOT = path.join(REPO_ROOT, "ids-platform");
const FRONTEND_ROOT = path.join(IDS_PLATFORM_ROOT, "frontend");
const VENV_PY = path.join(IDS_PLATFORM_ROOT, "venv", "Scripts", "python.exe");

// Packaged layout (electron-builder extraResources):
//   <resources>\engine\SOC-Engine\SOC-Engine.exe
//   <resources>\frontend  (compiled React build)
//   <resources>\models    (default trained models)
//   <resources>\defaults  (editable YAML/JSON config ships, response_rules.yaml,
//                          notification_rules.yaml, channel_settings.json)
const RESOURCES_ROOT = process.resourcesPath;
const PACKAGED_ENGINE = isPackaged
  ? path.join(RESOURCES_ROOT, "engine", "SOC-Engine", "SOC-Engine.exe")
  : null;

// ---------------------------------------------------------------------------
// Logging
// ---------------------------------------------------------------------------

const localAppData = process.env.LOCALAPPDATA || app.getPath("appData");
const dataRoot = isPackaged ? path.join(localAppData, PRODUCT) : path.join(REPO_ROOT, "desktop", ".runtime");
const dataDir = path.join(dataRoot, "data");
const confDir = path.join(dataRoot, "conf");
const logDir = path.join(dataRoot, "logs");

const desktopLogPath = path.join(logDir, "desktop.log");
const backendLogPath = path.join(logDir, "backend.log");

function log(...args) {
  const line = `[${new Date().toISOString()}] ${args.join(" ")}`;
  try { fs.appendFileSync(desktopLogPath, line + "\n"); } catch {}
  console.log(line);
}

function ensureDirs() {
  for (const dir of [dataRoot, dataDir, confDir, logDir, path.join(dataDir, "raw"), path.join(dataDir, "config")]) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

// ---------------------------------------------------------------------------
// Per-user config / secrets (never packaged)
// ---------------------------------------------------------------------------

const envFile = path.join(confDir, "app.env");

const frontendDistPath = () =>
  isPackaged ? path.join(RESOURCES_ROOT, "frontend") : path.join(FRONTEND_ROOT, "dist");

function readOrCreateEnv() {
  if (!fs.existsSync(envFile)) {
    const secret = crypto.randomBytes(48).toString("hex");
    const dbPath = `sqlite:///${dataDir.replace(/\\/g, "/")}/soc_platform.db`;
    const content = [
      "# Generated by SOC Platform on first run. Do not commit or distribute.",
      `JWT_SECRET_KEY=${secret}`,
      `DATABASE_URL=${dbPath}`,
      `MODEL_PATH=${path.join(dataDir, "models")}`,
      `DATA_PATH=${path.join(dataDir, "raw")}`,
      `FRONTEND_DIST=${frontendDistPath()}`,
      `RESPONSE_RULES_PATH=${path.join(dataDir, "config", "response_rules.yaml")}`,
      `NOTIFICATION_RULES_PATH=${path.join(dataDir, "config", "notification_rules.yaml")}`,
      `CHANNEL_SETTINGS_PATH=${path.join(dataDir, "config", "channel_settings.json")}`,
      "CORS_ORIGINS=*",
    ].join("\n") + "\n";
    fs.writeFileSync(envFile, content, { encoding: "utf8", mode: 0o600 });
    log("Created per-user config", envFile);
  }
  return envFile;
}

function readSecret() {
  try {
    const content = fs.readFileSync(envFile, "utf8");
    const m = content.match(/^JWT_SECRET_KEY=(.*)$/m);
    if (m) return m[1];
  } catch {}
  const secret = crypto.randomBytes(48).toString("hex");
  fs.appendFileSync(envFile, `\nJWT_SECRET_KEY=${secret}\n`);
  return secret;
}

function copyDirIfMissing(src, dest) {
  if (!fs.existsSync(src) || fs.existsSync(dest)) return;
  fs.cpSync(src, dest, { recursive: true });
  log(`Copied ${src} -> ${dest}`);
}

function copyFileIfMissing(src, dest) {
  if (!fs.existsSync(src) || fs.existsSync(dest)) return;
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
  log(`Copied ${src} -> ${dest}`);
}

// ---------------------------------------------------------------------------
// Process management
// ---------------------------------------------------------------------------

let engineProc = null;
let viteProc = null;

function killTree(proc) {
  if (!proc || !proc.pid) return;
  try {
    execFileSync("taskkill", ["/pid", String(proc.pid), "/T", "/F"], { stdio: "ignore" });
  } catch {
    try { proc.kill(); } catch {}
  }
}

function pipeChildOutput(child, targetPath) {
  const stream = fs.createWriteStream(targetPath, { flags: "a" });
  child.stdout?.on("data", (d) => stream.write(d));
  child.stderr?.on("data", (d) => stream.write(d));
  child.on("exit", (code) => {
    stream.write(`\n[desktop] process exited with code ${code}\n`);
    stream.end();
  });
}

function engineUrl() {
  return `http://127.0.0.1:${process.env.SOC_PLATFORM_PORT || DEFAULT_PORT}`;
}

function startEngine() {
  const env = { ...process.env };
  env.SOC_HOST = "127.0.0.1";
  env.SOC_PORT = String(process.env.SOC_PLATFORM_PORT || DEFAULT_PORT);
  env.SOC_LOG_LEVEL = "info";

  let child;
  if (isPackaged) {
    if (!PACKAGED_ENGINE || !fs.existsSync(PACKAGED_ENGINE)) {
      dialog.showErrorBox(
        "SOC Platform - Engine missing",
        `The security engine was not found at:\n${PACKAGED_ENGINE}\n\nReinstall the application.\n\nLog: ${desktopLogPath}`
      );
      app.exit(1);
      return null;
    }
    env.DATABASE_URL = `sqlite:///${dataDir.replace(/\\/g, "/")}/soc_platform.db`;
    env.MODEL_PATH = path.join(dataDir, "models");
    env.DATA_PATH = path.join(dataDir, "raw");
    env.JWT_SECRET_KEY = readSecret();
    env.FRONTEND_DIST = path.join(RESOURCES_ROOT, "frontend");
    env.RESPONSE_RULES_PATH = path.join(dataDir, "config", "response_rules.yaml");
    env.NOTIFICATION_RULES_PATH = path.join(dataDir, "config", "notification_rules.yaml");
    env.CHANNEL_SETTINGS_PATH = path.join(dataDir, "config", "channel_settings.json");
    env.CORS_ORIGINS = "*";

    log("Spawning packaged engine:", PACKAGED_ENGINE, "cwd=" + dataDir);
    child = spawn(PACKAGED_ENGINE, [], { cwd: dataDir, env, windowsHide: true });
  } else {
    if (!fs.existsSync(VENV_PY)) {
      dialog.showErrorBox(
        "SOC Platform - Developer setup incomplete",
        `Backend virtualenv not found at:\n${VENV_PY}\n\nRun setup.bat (or create venv and install requirements) first.`
      );
      app.exit(1);
      return null;
    }
    log("Spawning dev engine:", VENV_PY, "desktop_entry.py", "cwd=" + IDS_PLATFORM_ROOT);
    child = spawn(VENV_PY, ["desktop_entry.py"], { cwd: IDS_PLATFORM_ROOT, env, windowsHide: true });
  }

  pipeChildOutput(child, backendLogPath);
  engineProc = child;
  child.on("exit", (code) => {
    log("Engine process exited with code", code);
    engineProc = null;
  });
  child.on("error", (err) => {
    log("Engine spawn error:", err.message);
    dialog.showErrorBox("SOC Platform - Engine failed to start", `Could not start the security engine: ${err.message}`);
  });
  return child;
}

// ---------------------------------------------------------------------------
// Readiness checks
// ---------------------------------------------------------------------------

function waitForHttp(url, timeoutMs, pollMs) {
  const deadline = Date.now() + timeoutMs;
  return new Promise((resolve) => {
    const attempt = () => {
      const req = http.get(url, { timeout: 2000 }, (res) => {
        res.resume();
        resolve(true);
      });
      req.on("error", () => attemptAgain());
      req.on("timeout", () => {
        req.destroy();
        attemptAgain();
      });
    };
    const attemptAgain = () => {
      if (Date.now() >= deadline) { resolve(false); return; }
      setTimeout(attempt, pollMs);
    };
    attempt();
  });
}

async function ensureVite() {
  const url = `http://localhost:${VITE_PORT}`;
  if (await waitForHttp(url, 3000, 200)) return true;

  log("Starting Vite dev server...");
  viteProc = spawn("npm.cmd", ["run", "dev"], { cwd: FRONTEND_ROOT, shell: true, windowsHide: true });
  pipeChildOutput(viteProc, path.join(logDir, "vite.log"));
  viteProc.on("exit", (code) => { log("Vite exited with code", code); viteProc = null; });

  const ok = await waitForHttp(url, HEALTH_TIMEOUT_MS, HEALTH_POLL_MS);
  if (!ok) {
    dialog.showErrorBox(
      "SOC Platform - Frontend did not start",
      `The Vite dev server did not become ready in time.\n\nLog: ${desktopLogPath}`
    );
    app.exit(1);
  }
  return ok;
}

// ---------------------------------------------------------------------------
// Window
// ---------------------------------------------------------------------------

function createWindow(url) {
  const win = new BrowserWindow({
    width: 1440,
    height: 900,
    minWidth: 1024,
    minHeight: 640,
    show: false,
    title: "SOC Platform",
    autoHideMenuBar: true,
    backgroundColor: "#0f172a",
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      preload: path.join(__dirname, "preload.cjs"),
    },
  });

  win.once("ready-to-show", () => win.show());
  win.setMenuBarVisibility(!isPackaged);
  win.loadURL(url);
  win.webContents.on("did-fail-load", (_e, code, desc, validatedURL) => {
    log("Window failed to load", validatedURL, code, desc);
  });
  return win;
}

// ---------------------------------------------------------------------------
// Lifecycle
// ---------------------------------------------------------------------------

let mainWindow = null;

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.quit();
} else {
  app.on("second-instance", () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
  });

  app.whenReady().then(async () => {
    ensureDirs();
    readOrCreateEnv();
    log("SOC Platform starting", { packaged: isPackaged, dataRoot, engine: PACKAGED_ENGINE || VENV_PY });

    if (isPackaged) {
      // Seed writable user-data copies of default resources on first run.
      copyDirIfMissing(path.join(RESOURCES_ROOT, "models"), path.join(dataDir, "models"));
      copyFileIfMissing(
        path.join(RESOURCES_ROOT, "defaults", "response_rules.yaml"),
        path.join(dataDir, "config", "response_rules.yaml")
      );
      copyFileIfMissing(
        path.join(RESOURCES_ROOT, "defaults", "notification_rules.yaml"),
        path.join(dataDir, "config", "notification_rules.yaml")
      );
      copyFileIfMissing(
        path.join(RESOURCES_ROOT, "defaults", "channel_settings.json"),
        path.join(dataDir, "config", "channel_settings.json")
      );
    }

    startEngine();
    const ok = await waitForHttp(`${engineUrl()}/health`, HEALTH_TIMEOUT_MS, HEALTH_POLL_MS);
    if (!ok) {
      log("Engine health check timed out");
      dialog.showErrorBox(
        "SOC Platform - Engine did not start",
        `The network security engine did not become ready in time.\n\nCheck the backend log:\n${backendLogPath}\n\nDesktop log:\n${desktopLogPath}`
      );
      app.exit(1);
      return;
    }
    log("Engine is healthy at", engineUrl());

    if (process.env.SOC_SMOKE === "1") {
      if (!isPackaged) await ensureVite();
      log("SMOKE_OK engine ready");
      app.quit();
      return;
    }

    let targetUrl;
    if (!isPackaged) {
      await ensureVite();
      targetUrl = `http://localhost:${VITE_PORT}`;
    } else {
      targetUrl = engineUrl();
    }

    mainWindow = createWindow(targetUrl);
    if (process.env.SOC_DEV_TOOLS === "1") {
      mainWindow.webContents.openDevTools({ mode: "detach" });
    }
    mainWindow.on("closed", () => { mainWindow = null; });
  });

  app.on("window-all-closed", () => {
    app.quit();
  });

  app.on("before-quit", () => {
    if (engineProc) killTree(engineProc);
    if (viteProc) killTree(viteProc);
  });

  app.on("quit", () => {
    if (engineProc) killTree(engineProc);
    if (viteProc) killTree(viteProc);
  });
}